from .bst import BST
from .avl import AVL
from .max_heap import Heap
from .segment_tree import ST
from .linked_list import LinkedList
from .double_linked_list import DoubleLinkedList
from .queue import Queue
from .stack import Stack
from .trie import Trie
from .graph import Graph
from .wgraph import WGraph
